language: R
sudo: false
cache: packages
r: bioc-release
before_script:
  - Rscript -e 'install.packages("RUnit")'
addons:
  apt:
    packages:
    - libgsl2
    - gsl-bin
    - libgsl-dbg
    - libgsl-dev